framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: session.handler.pdo
        gc_maxlifetime: 21600
        cookie_secure: auto
        cookie_samesite: lax

    disallow_search_engine_index: false

    #esi: true
    #fragments: true
    php_errors:
        log: true
