# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
parameters:
  s3_client_region: "%env(AWS_DEFAULT_REGION)%"
  s3_client_prefix: data

services:
  s3_client:
    class: Aws\S3\S3Client
    arguments:
      -
        version: 'latest'
        region: "%env(AWS_DEFAULT_REGION)%"

oneup_flysystem:
  adapters:
    s3_adapter:
      awss3v3:
        client: s3_client
        bucket: "%env(S3_BUCKET)%"
        prefix: "%env(S3_PREFIX)%data/"
    default_adapter:
      local:
        directory: '%kernel.cache_dir%/flysystem'
  filesystems:
    default_filesystem:
      adapter: s3_adapter
      alias: storage_filesystem
