twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        env: '%kernel.environment%'
        asset_version: '%asset_version%'
        s3_web_url: '%s3_web_url%'