# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
services:
  s3_client:
    class: Aws\S3\S3Client
    arguments:
      -
        version: 'latest'
        region: "%env(AWS_DEFAULT_REGION)%"
        credentials:
          key: "%env(S3_CLIENT_KEY)%"
          secret: "%env(S3_CLIENT_SECRET)%"